name: NuGet Pack & Upload to Google Drive

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest

    env:
      PROJECT_NAME: 'DAL'
      GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet Packages
      id: restore_nuget
      run: nuget restore DAL.sln
      shell: pwsh

    - name: Notify Google Chat - Restore Failure
      if: failure()
      run: |
        $body = @{ text = "❌ Restore NuGet Packages Failed for $env:PROJECT_NAME" } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "$env:GOOGLE_CHAT_WEBHOOK_URL" -Method Post -ContentType 'application/json' -Body $body
      shell: pwsh

    - name: Build Solution (Release)
      id: build_solution
      run: msbuild DAL.sln /p:Configuration=Release /p:Platform="Any CPU"
      shell: pwsh

    - name: Notify Google Chat - Build Failure
      if: failure()
      run: |
        $body = @{ text = "❌ Build Failed for $env:PROJECT_NAME" } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "$env:GOOGLE_CHAT_WEBHOOK_URL" -Method Post -ContentType 'application/json' -Body $body
      shell: pwsh

    - name: Pack NuGet Package
      id: nuget_pack
      run: nuget pack DAL.csproj -OutputDirectory ./nupkgs -Properties Configuration=Release
      shell: pwsh

    - name: Notify Google Chat - Pack Success
      if: success()
      run: |
        $body = @{ text = "✅ NuGet Pack Success: $env:PROJECT_NAME.nupkg created." } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "$env:GOOGLE_CHAT_WEBHOOK_URL" -Method Post -ContentType 'application/json' -Body $body
      shell: pwsh

    - name: Notify Google Chat - Pack Failure
      if: failure()
      run: |
        $body = @{ text = "❌ NuGet Pack Failed for $env:PROJECT_NAME" } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "$env:GOOGLE_CHAT_WEBHOOK_URL" -Method Post -ContentType 'application/json' -Body $body
      shell: pwsh

    - name: Upload to Google Drive
      if: success()
      uses: Jodebu/upload-to-google-drive@v1
      with:
        target: './nupkgs'
        credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        folderId: '1jN23YIU6aclDiZhFZliCLxzdW76-39fo'

    - name: Notify Google Chat - Upload Success
      if: success()
      run: |
        $body = @{ text = "☁️ Upload to Google Drive Successful!\n\n🔗 https://drive.google.com/drive/u/0/folders/1jN23YIU6aclDiZhFZliCLxzdW76-39fo" } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "$env:GOOGLE_CHAT_WEBHOOK_URL" -Method Post -ContentType 'application/json' -Body $body
      shell: pwsh

    - name: Notify Google Chat - Pipeline Failed
      if: failure()
      run: |
        $body = @{ text = "❌ Pipeline Failed for $env:PROJECT_NAME.\nPlease check GitHub Actions log." } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "$env:GOOGLE_CHAT_WEBHOOK_URL" -Method Post -ContentType 'application/json' -Body $body
      shell: pwsh
