name: NuGet Pack & Upload to Google Drive

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pack-push:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: Calculate Version (Auto Increment)
      id: versioning
      run: |
        $lastTag = git describe --tags --abbrev=0
        Write-Output "Last Tag: $lastTag"

        $versionParts = $lastTag.TrimStart('v').Split('.')
        $major = [int]$versionParts[0]
        $minor = [int]$versionParts[1]
        $patch = [int]$versionParts[2] + 1

        $newVersion = "$major.$minor.$patch"
        Write-Output "New Version: $newVersion"

        echo "nuget_version=$newVersion" >> $env:GITHUB_ENV

    - name: Restore NuGet Packages
      run: nuget restore DAL.sln

    - name: Build Solution
      run: msbuild DAL.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Pack NuGet Package
      run: |
        nuget pack DAL.csproj `
          -OutputDirectory ./nupkgs `
          -Properties Configuration=Release `
          -Version $env:nuget_version

    - name: Upload NuGet Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGetPackage
        path: ./nupkgs/*.nupkg
