name: Build and Upload NuGet to Google Drive

on:
  push:
    branches:
      - master

jobs:
  build-pack-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: latest

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'

    - name: Restore NuGet Packages
      run: nuget restore DAL.sln

    - name: Build Solution
      run: msbuild DAL.csproj /p:Configuration=Release /p:Platform="Any CPU"

    - name: Pack NuGet Package
      run: nuget pack DAL.csproj -Properties Configuration=Release -OutputDirectory ./nupkgs

    - name: Upload to Google Drive
      uses: Jodebu/upload-to-google-drive@v1
      with:
        target: './nupkgs'
        credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
        folderId: 'YOUR_GOOGLE_DRIVE_FOLDER_ID'
