name: NuGet Pack & Upload to Google Drive (.NET Framework 4.8.1)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    
    - name: Run nuget pack
      id: nuget_pack
      shell: pwsh
      run: |
        nuget pack DAL.csproj -OutputDirectory ./nupkgs 2>&1 | Tee-Object -FilePath nuget_pack.log
        if ($LASTEXITCODE -ne 0) { exit 1 }

    - name: Build DAL Project
      shell: pwsh
      run: |
        msbuild DAL.csproj /p:Configuration=Release

    - name: Notify Google Chat - Success
      if: steps.nuget_pack.outcome == 'success'
      shell: pwsh
      run: |
        $body = @{ text = "✅ NuGet Pack Success: DAL.nupkg created." } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $body

    - name: Notify Google Chat - Failure
      if: steps.nuget_pack.outcome == 'failure'
      shell: pwsh
      run: |
        $errorLog = Get-Content nuget_pack.log -Raw
        if ($errorLog.Length -gt 3500) {
          $errorLog = $errorLog.Substring(0, 3500) + "`n... (truncated)"
        }
        $body = @{ text = "❌ DAL.nupkg Creation Failed!\n```\n$errorLog\n```" } | ConvertTo-Json -Depth 10
        Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $body


    - name: Upload to Google Drive
      if: steps.nuget_pack.outcome == 'success'
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        credentials_json: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        path: ./nupkgs/*.nupkg
        destination: drive://1jN23YIU6aclDiZhFZliCLxzdW76-39fo/
