name: NuGet Pack & Upload to Google Drive (.NET Framework 4.8.1)

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Build Project (.NET Framework 4.8.1)
      run: |
        &"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" DAL.csproj /p:Configuration=Release

    - name: Run nuget spec
      run: nuget spec DAL.csproj

    - name: Run nuget pack
      id: nuget_pack
      run: nuget pack DAL.csproj -OutputDirectory ./nupkgs
      continue-on-error: true

    - name: Notify Google Chat - Success
      if: steps.nuget_pack.outcome == 'success'
      run: |
        $body = @{ text = "✅ NuGet Pack Success: DAL.nupkg created." } | ConvertTo-Json
        Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $body

    - name: Notify Google Chat - Failure
      if: steps.nuget_pack.outcome == 'failure'
      run: |
        $body = @{ text = "❌ NuGet Pack Failed! DAL.nupkg not created." } | ConvertTo-Json
        Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $body

    - name: Upload to Google Drive
      if: steps.nuget_pack.outcome == 'success'
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        credentials_json: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        path: ./nupkgs/*.nupkg
        destination: drive://1jN23YIU6aclDiZhFZliCLxzdW76-39fo/
